config/routes.rb
Rails.application.routes.draw do
  resources :creatives do
    member do
      get 'vast_xml', format: 'xml'
    end
  end

  get 'vast_xml/sample_icon_base_text', format: 'xml'
  get 'vast_xml/sample_video_base_text', format: 'xml'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/creative.rb
class Creative < ApplicationRecord
  has_one :vast_structure, dependent: :destroy

  accepts_nested_attributes_for :vast_structure

  validates :title, presence: true
end

app/controllers/creatives_controller.rb
class CreativesController < ApplicationController
  before_action :set_creative, only: %i[ show edit update destroy vast_xml ]

  # GET /creatives or /creatives.json
  def index
    @creatives = Creative.all
  end

  # GET /creatives/1 or /creatives/1.json
  def show
  end

  # GET /creatives/new
  def new
    @creative = Creative.new
    @creative.build_vast_structure
    @creative.vast_structure.linear_structures.build
    @creative.vast_structure.linear_structures.first.build_media_file_group
    3.times do
      is = @creative.vast_structure.linear_structures.first.icon_structures.build
      is.build_icon_resource
    end
  end

  # GET /creatives/1/edit
  def edit
  end

  # POST /creatives or /creatives.json
  def create
    @creative = Creative.new(creative_params)

    respond_to do |format|
      if @creative.save
        format.html { redirect_to creative_url(@creative), notice: "Creative was successfully created." }
        format.json { render :show, status: :created, location: @creative }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @creative.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /creatives/1 or /creatives/1.json
  def update
    respond_to do |format|
      if @creative.update(creative_params)
        format.html { redirect_to creative_url(@creative), notice: "Creative was successfully updated." }
        format.json { render :show, status: :ok, location: @creative }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @creative.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /creatives/1 or /creatives/1.json
  def destroy
    @creative.destroy

    respond_to do |format|
      format.html { redirect_to creatives_url, notice: "Creative was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def vast_xml
    options = {it: params[:it]}
    render xml: @creative.vast_structure.to_vast_xml(options)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_creative
      @creative = Creative.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def creative_params
      params.require(:creative).permit(
        :title,
        vast_structure_attributes: [
          :id,
          :ad_title,
          linear_structures_attributes: [
            :id,
            :_destroy,
            media_file_group_attributes: [
              :id,
              :_destroy,
              :video_upload_format,
              :external_file_url_text,
              :original_media_file,
              :overlay_image_file,
              :qr_url
            ],
            icon_structures_attributes: [
              :id,
              :program,
              :x_position,
              :y_position,
              :offset,
              :duration,
              :_destroy,
              icon_resource_attributes: [
                :id,
                :_destroy,
                :format,
                :icon_file,
                :ov_default_text,
                :qr_url
              ]
            ]
          ]
        ]
      )
    end
end

app/helpers/creatives_helper.rb
module CreativesHelper
end

app/views/creatives/_form.html.haml
= form_for(@creative) do |f|
  - if @creative.errors.any?
    #error_explanation
      %h2= "#{pluralize(@creative.errors.count, "error")} prohibited this creative from being saved:"
      %ul
        - @creative.errors.full_messages.each do |message|
          %li= message

  .field.is-horizontal
    .field-label.is-normal
      %label.label クリエイティブ名
    .field-body
      .field
        .control
          = f.text_field :title, class: 'input'
        .help VASTには出力されない
    
  = f.fields_for :vast_structure do |vs|
    .field.is-horizontal
      .field-label.is-normal
        %label.label AdTitle
      .field-body
        .field
          .control
            = vs.text_field :ad_title, class: 'input', placeholder: "e.g. 商品名"

    = vs.fields_for :linear_structures do |ls|
      %br
      %br

      = ls.fields_for :media_file_group do |mfg|
        .field.is-horizontal
          .field-label
            %label.label 動画エンコード
          .field-body
            .field.is-narrow
              %control
                %label.radio
                  = mfg.radio_button :video_upload_format, :external_host
                  外部ホストをエンコードなしで利用
                %br
                %label.radio
                  = mfg.radio_button :video_upload_format, :simple_video_upload
                  アップロードファイル
                %br
                %label.radio
                  = mfg.radio_button :video_upload_format, :custom_overlay_image
                  アップロードファイル + 画像オーバーレイ
                %br
                %label.radio
                  = mfg.radio_button :video_upload_format, :qr_code_image
                  アップロードファイル + QRコード自動生成オーバーレイ
 
        .field.is-horizontal
          .field-label.is-normal
            %label.label 外部ファイルURL
          .field-body
            .field
              .control
                = mfg.text_field :external_file_url_text, class: 'input'
        .field.is-horizontal
          .field-label.is-normal
            %label.label 動画ファイル
          .field-body
            .file
              %label.file-label
                = mfg.file_field :original_media_file, class: 'file-input'
                %span.file-cta
                  %span.file-label
                    Choose a file...
        .field.is-horizontal
          .field-label.is-normal
            %label.label オーバーレイ画像
          .field-body
            .file
              %label.file-label
                = mfg.file_field :overlay_image_file, class: 'file-input'
                %span.file-cta
                  %span.file-label
                    Choose a file...
        .field.is-horizontal
          .field-label.is-normal
            %label.label QRリンク先URL
          .field-body
            .field
              .control
                = mfg.text_field :qr_url, class: 'input', placeholder: "https://"
 
      %br
      %br

      = ls.simple_fields_for :icon_structures do |is|
        = is.simple_fields_for :icon_resource do |ir|
          .box
            .field.is-horizontal
              .field-label.is-normal
                %label.label アイコン名
              .field-body
                .field
                  .control
                    = is.text_field :program, class: 'input'
            .field.is-horizontal
              .field-label.is-normal
                %label.label フォーマット
              .field-body
                .field
                  .control.select
                    = ir.select :format, IconResource.format.options
            .field.is-horizontal
              .field-label.is-normal
                %label.label アイコン画像
              .field-body
                .file
                  %label.file-label
                    = ir.file_field :icon_file, class: 'file-input'
                    %span.file-cta
                      %span.file-label
                        Choose a file...
            .field.is-horizontal
              .field-label.is-normal
                %label.label 横の位置
              .field-body
                .field
                  .control
                    = is.text_field :x_position, class: 'input'
                  .help left もしくは right もしくは 左端からのpx数 
            .field.is-horizontal
              .field-label.is-normal
                %label.label 縦の位置
              .field-body
                .field
                  .control
                    = is.text_field :y_position, class: 'input'
                  .help top もしくは bottom もしくは 上端からのpx数 
            .field.is-horizontal
              .field-label.is-normal
                %label.label 表示開始時間(秒)
              .field-body
                .field
                  .control
                    = is.number_field :offset, class: 'input'
            .field.is-horizontal
              .field-label.is-normal
                %label.label 表示時間(秒)
              .field-body
                .field
                  .control
                    = is.number_field :duration, class: 'input'
            .field.is-horizontal
              .field-label.is-normal
                %label.label デフォルト文言
              .field-body
                .field
                  .control
                    = ir.text_field :ov_default_text, class: 'input'
                  .help アイコンに文言をオーバーレイ表示させる場合のデフォルト文言
            .field.is-horizontal
              .field-label.is-normal
                %label.label QRリンク先URL
              .field-body
                .field
                  .control
                    = ir.text_field :qr_url, class: 'input'
                  .help アイコンにQRコードをオーバーレイ表示させる場合のURL

  .field.is-horizontal
    .field-label
      / Left empty for spacing
    .field-body
      .field
        .control
          = f.submit "作成", class: "button is-info"

app/views/creatives/edit.html.haml
%h1.title
  Editing creative

= render 'form'

= link_to 'Show', @creative
\|
= link_to 'Back', creatives_path

app/views/creatives/index.html.haml
%h1.title Creative 一覧

%table.table
  %thead
    %tr
      %th ID
      %th Title
      %th
      %th
      %th

  %tbody
    - @creatives.each do |creative|
      %tr
        %td= creative.id
        %td= creative.title
        %td= link_to 'Show', creative
        %td= link_to 'Edit', edit_creative_path(creative)
        %td= button_to 'Destroy', creative, method: :delete, data: { confirm: 'Are you sure?' }

app/views/creatives/new.html.haml
%h1.title
  Creative 新規追加

= render 'form'

app/views/creatives/show.html.haml
- mfg = @creative.vast_structure.linear_structures.first.media_file_group

%p#notice= notice

%h1.title
  = "Creative ##{@creative.id} #{@creative.title}"

%h2.subtitle Creative情報
.box
  .field.is-horizontal
    .field-label
      %label.label AdTitle
    .field-body
      = @creative.vast_structure.ad_title

%h2.subtitle MediaFile
.box
  .field.is-horizontal
    .field-label
      %label.label Duration
    .field-body
      = mfg.duration

  .field.is-horizontal
    .field-label
      %label.label Video Upload Format
    .field-body
      = mfg.video_upload_format

  .field.is-horizontal
    .field-label
    .field-body
      - if mfg.video_upload_format.external_host?
        - mfg.external_media_files.each do |mfs|
          %table.table
            %thead
              %tr
                %th file_name
                %th mime type
                %th widh
                %th height
                %th bitrate
                %th codec
                %th duration
                %th file size
            %tbody
              %tr
                %td= link_to(File.basename(mfs.external_host_url), mfs.external_host_url)
                %td= mfs.mime_type
                %td= mfs.width
                %td= mfs.height
                %td= "#{(mfs.bitrate / (2 ** 10).to_f).round(-2)}kbps"
                %td= mfs.codec
                %td= mfs.duration.round(3)
                %td= "#{(mfs.file_size / (2 ** 20).to_f).round(2)}MB"
      - else
        %p
          %b Original Media File:
          = mfg.original_media_file.to_s

%h2.subtitle Icon
.box
  %div{style: "margin-left: 20px"}
    %table.table
      %thead
        %tr
          %th{rowspan: 2} ID
          %th Program
          %th Format
          %th Icon Image
          %th mime_type
          %th width
          %th height
        %tr
          %th x_position
          %th y_position
          %th offset
          %th duration
          %th Default Text
          %th URL
      %tbody
        - @creative.vast_structure.linear_structures.first.icon_structures.each do |is|
          %tr
            %td{rowspan: 2}= is.id
            %td= is.program
            %td= is.icon_resource.format
            %td= link_to(image_tag(is.icon_resource.icon_url, height: "100"), is.icon_resource.icon_url)
            %td= is.icon_resource.mime_type
            %td= is.icon_resource.width
            %td= is.icon_resource.height
          %tr
            %td= is.x_position.presence || "--"
            %td= is.y_position.presence || "--"
            %td= is.offset.presence || "--"
            %td= is.duration.presence || "--"
            %td= is.icon_resource.ov_default_text.presence || "--"
            %td= is.icon_resource.qr_url.presence || "--"

%br
%h2.subtitle VAST Output
%p
  vast url:
  = vast_xml_creative_url(@creative)
%p
  option it: アイコンオーバーレイテキスト

%textarea.textarea{cols: 80, rows: 30}
  = @creative.vast_structure.to_vast_xml
%br
= link_to 'Edit', edit_creative_path(id: @creative)
\|
= link_to 'Back', creatives_path